"""Phase 9.18.S9q-β-lattice — Lattice characterization of Λ_M, Λ_{O_6}.

β-2 (first probe of the β-thrust). Companion to α-quater.

Goal: characterize as integer lattices in V_std ∩ Z^9 = {v ∈ Z^9 : Σv_i = 0}
(rank 8) the two sublattices

    Λ_M    = Z⟨ orb(M)    ⟩,   |orb(M)|    = 756
    Λ_{O_6} = Z⟨ orb(O_6) ⟩,   |orb(O_6)| = 3024

generated by the two G*-orbits identified in §8.25.decies / §8.25.duodecies.

Concrete questions answered:

  1. Saturation:    Λ_M = V_std ∩ Z^9 = A_8-lattice ?
                    (i.e. does the orbit of M generate the whole rank-8
                    sub-lattice of integer zero-sum vectors?)
  2. Inclusion:     Λ_{O_6} ⊆ Λ_M ?  (already a lattice consequence of the
                    3-term witness U_8 = -A-B-C of §8.25.decies.1)
  3. Index:         [Λ_M : Λ_{O_6}] = ?
  4. SNF:           elementary divisors of both M-orbit and O_6-orbit
                    matrices (756×9 and 3024×9), whose Smith normal forms
                    expose the quotient lattice structure.
  5. Witness:       direct verification that the 3-term decomposition
                    U_8 = -A-B-C lies in Λ_M.

Method: build action tables for M and O_6, stack into integer matrices,
compute Hermite/Smith normal forms via sympy.matrices.normalforms.

Output: data/phase_9_18_S9q_beta_lattice.json + _output.txt
"""
from __future__ import annotations
import json
import sys
import time
from pathlib import Path

import numpy as np
import sympy as sp
from sympy.matrices.normalforms import smith_normal_form, hermite_normal_form

ROOT = Path(__file__).resolve().parents[2]  # <repo>/scripts/legacy/ -> <repo>/
sys.path.insert(0, str(ROOT / "scripts" / "legacy"))

from phase_9_18_S9w_S9y_closure_audit import (  # noqa: E402
    ACTION_IDX,
    ACTION_SIGN,
)

DATA = ROOT / "data"
N_GSTAR = ACTION_IDX.shape[0]
assert N_GSTAR == 725760, N_GSTAR


# --------------------------------------------------------------------
# Build the orbit of v under all 725760 actions.
# --------------------------------------------------------------------

def orbit(vec):
    """Full G*-orbit of vec, as a (|orb|, 9) int array of distinct rows."""
    v = np.asarray(vec, dtype=np.int64)
    permuted = v[ACTION_IDX.astype(np.int64)]                      # (N,9)
    signed = permuted * ACTION_SIGN[:, None].astype(np.int64)      # (N,9)
    # Deduplicate rows.
    uniq = np.unique(signed, axis=0)
    return uniq


# --------------------------------------------------------------------
# Lattice tools.
# --------------------------------------------------------------------

def lattice_invariants(M_int, label):
    """Compute SNF, HNF, rank and elementary divisors of an int matrix.

    M_int: numpy int array of shape (k, 9), where rows are lattice generators.
    Returns dict with rank, elementary divisors, and a sympy HNF (upper).
    """
    print(f"  [{label}] matrix shape = {M_int.shape}", flush=True)
    M = sp.Matrix(M_int.tolist())

    t0 = time.time()
    H = hermite_normal_form(M.T)        # HNF of transpose: lattice in Z^9.
    t1 = time.time()
    print(f"  [{label}] HNF computed in {t1 - t0:.2f}s, "
          f"shape={H.shape}", flush=True)

    # Rank = number of nonzero columns of HNF.
    nonzero_cols = [j for j in range(H.shape[1])
                    if any(H[i, j] != 0 for i in range(H.shape[0]))]
    rank = len(nonzero_cols)
    print(f"  [{label}] rank = {rank}", flush=True)

    # Elementary divisors via SNF of the HNF (square sublatt).
    H_red = H[:, nonzero_cols]      # 9 × rank
    print(f"  [{label}] H_red shape = {H_red.shape}", flush=True)
    t0 = time.time()
    S = smith_normal_form(H_red)
    t1 = time.time()
    print(f"  [{label}] SNF computed in {t1 - t0:.2f}s", flush=True)
    elem_div = [int(S[i, i]) for i in range(min(S.shape))]
    elem_div = [d for d in elem_div if d != 0]
    print(f"  [{label}] elementary divisors = {elem_div}", flush=True)
    print(f"  [{label}] det of full sublatt (rank=8 expected) = "
          f"{np.prod(elem_div) if rank == 8 else 'n/a'}", flush=True)

    return {
        "rank": rank,
        "elementary_divisors": elem_div,
        "hnf": [[int(H[i, j]) for j in range(H.shape[1])]
                for i in range(H.shape[0])],
    }


def reduce_in_lattice(target_vec, generators_int):
    """Decide if target_vec ∈ Z⟨generators⟩ using HNF.

    target_vec: (9,) int array.
    generators_int: (k, 9) int array.
    Returns dict {in_lattice: bool, residue: list[int]}.
    """
    G = sp.Matrix(generators_int.tolist())
    H = hermite_normal_form(G.T)            # 9 × rank   (column HNF basis)
    # For each col of H find a pivot row.
    rank = H.shape[1]
    pivots = []
    for j in range(rank):
        for i in range(H.shape[0] - 1, -1, -1):
            if H[i, j] != 0:
                pivots.append(i)
                break
    target = sp.Matrix([int(x) for x in target_vec])
    residue = sp.Matrix(target)
    for j in reversed(range(rank)):
        i = pivots[j]
        h = H[i, j]
        # We need residue[i] divisible by h (after reducing higher-rank
        # pivots).
        if h == 0:
            continue
        q = sp.Rational(residue[i], h)
        if q.q != 1:
            return {"in_lattice": False,
                    "residue": [int(x) for x in residue]}
        residue = residue - int(q) * H[:, j]
    in_latt = all(residue[i] == 0 for i in range(9))
    return {"in_lattice": in_latt,
            "residue": [int(x) for x in residue]}


def index_of_sublattice(big_int, small_int):
    """Compute [Λ(big) : Λ(small)] when both have the same rank.

    Returns int (or None if the index is infinite, i.e. rank mismatch).
    """
    Bb = sp.Matrix(big_int.tolist())
    Bs = sp.Matrix(small_int.tolist())
    Hb = hermite_normal_form(Bb.T)
    Hs = hermite_normal_form(Bs.T)
    if Hb.shape[1] != Hs.shape[1]:
        return None
    # det(Hb) and det(Hs) both nonzero on full-rank sublatt.
    nonzero_b = [j for j in range(Hb.shape[1])
                 if any(Hb[i, j] != 0 for i in range(Hb.shape[0]))]
    nonzero_s = [j for j in range(Hs.shape[1])
                 if any(Hs[i, j] != 0 for i in range(Hs.shape[0]))]
    Hb_sq = Hb[:, nonzero_b]
    Hs_sq = Hs[:, nonzero_s]
    if Hb_sq.shape[1] != Hs_sq.shape[1]:
        return None
    Sb = smith_normal_form(Hb_sq)
    Ss = smith_normal_form(Hs_sq)
    db = 1
    for i in range(min(Sb.shape)):
        if Sb[i, i] != 0:
            db *= int(Sb[i, i])
    ds = 1
    for i in range(min(Ss.shape)):
        if Ss[i, i] != 0:
            ds *= int(Ss[i, i])
    if ds % db != 0:
        return None  # not a sub-lattice
    return ds // db


# --------------------------------------------------------------------
# Run.
# --------------------------------------------------------------------

def main():
    print("=" * 78)
    print("Phase 9.18.S9q-β-lattice — Lattice characterization of Λ_M, Λ_{O_6}")
    print("=" * 78)
    print(flush=True)

    M_rep = (-1, -1, 0, 0, 0, 0, 0, 1, 1)
    O6_rep = (-2, -1, 0, 0, 0, 0, 0, 1, 2)

    # Build orbits.
    print("  building orb(M) …", flush=True)
    orb_M = orbit(M_rep)
    print(f"  |orb(M)| = {orb_M.shape[0]}", flush=True)
    assert orb_M.shape[0] == 756

    print("  building orb(O_6) …", flush=True)
    orb_O6 = orbit(O6_rep)
    print(f"  |orb(O_6)| = {orb_O6.shape[0]}", flush=True)
    assert orb_O6.shape[0] == 3024

    # Sanity check: every row sums to 0 (V_std).
    assert np.all(orb_M.sum(axis=1) == 0), "orb(M) not in V_std!"
    assert np.all(orb_O6.sum(axis=1) == 0), "orb(O_6) not in V_std!"
    print("  all rows are zero-sum (V_std) ✓", flush=True)

    # ---- Question 1: rank & saturation of Λ_M.
    print()
    print("-" * 78)
    print("  Q1. Rank and saturation of Λ_M")
    print("-" * 78, flush=True)
    inv_M = lattice_invariants(orb_M, "Λ_M")

    # Reference lattice A_8 = V_std ∩ Z^9: basis e_i - e_{i+1}, i=0..7.
    A8 = np.zeros((8, 9), dtype=np.int64)
    for i in range(8):
        A8[i, i] = 1
        A8[i, i + 1] = -1
    inv_A8 = lattice_invariants(A8, "A_8 (ref)")

    saturated_M = (inv_M["rank"] == 8 and
                   inv_M["elementary_divisors"] == [1] * 8)
    print(f"  Λ_M saturates V_std ∩ Z^9 ?  {saturated_M}", flush=True)

    # ---- Question 2: rank & saturation of Λ_{O_6}.
    print()
    print("-" * 78)
    print("  Q2. Rank and elementary divisors of Λ_{O_6}")
    print("-" * 78, flush=True)
    inv_O6 = lattice_invariants(orb_O6, "Λ_{O_6}")
    saturated_O6 = (inv_O6["rank"] == 8 and
                    inv_O6["elementary_divisors"] == [1] * 8)
    print(f"  Λ_{{O_6}} saturates V_std ∩ Z^9 ?  {saturated_O6}", flush=True)

    # ---- Question 3: inclusion Λ_{O_6} ⊆ Λ_M.
    print()
    print("-" * 78)
    print("  Q3. Inclusion Λ_{O_6} ⊆ Λ_M  (test on every orbit-rep)")
    print("-" * 78, flush=True)
    # If both have rank 8 and Λ_{O_6} ⊆ Λ_M, the index is finite. For
    # efficiency test only the rep U8 = O6_rep then conclude by symmetry
    # (G* acts on both Λ_M and orb(O_6), so Λ_M is G*-invariant, so
    # checking one rep suffices).
    res = reduce_in_lattice(np.array(O6_rep, dtype=np.int64), orb_M)
    print(f"  O_6_rep ∈ Λ_M ?  {res['in_lattice']}",
          flush=True)
    if not res["in_lattice"]:
        print(f"  residue = {res['residue']}", flush=True)

    # ---- Question 4: index [Λ_M : Λ_{O_6}].
    print()
    print("-" * 78)
    print("  Q4. Index [Λ_M : Λ_{O_6}]")
    print("-" * 78, flush=True)
    if res["in_lattice"]:
        idx = index_of_sublattice(orb_M, orb_O6)
        print(f"  [Λ_M : Λ_{{O_6}}] = {idx}", flush=True)
    else:
        idx = None
        print("  not a sublattice — index undefined", flush=True)

    # ---- Question 5: 3-term witness verification (§8.25.decies.1).
    print()
    print("-" * 78)
    print("  Q5. 3-term witness  U_8 = -A - B - C  with A,B,C ∈ orb(M)")
    print("-" * 78, flush=True)
    U8 = np.array((0, 0, 2, -2, 1, -1, 0, 0, 0), dtype=np.int64)
    A = np.array((0, -1, 0, 0, -1, 1, 0, 1, 0), dtype=np.int64)
    B = np.array((0, 0, -1, 1, 1, 0, 0, -1, 0), dtype=np.int64)
    C = np.array((0, 1, -1, 1, -1, 0, 0, 0, 0), dtype=np.int64)

    rows_M_set = {tuple(row.tolist()) for row in orb_M}
    A_in = tuple(A.tolist()) in rows_M_set
    B_in = tuple(B.tolist()) in rows_M_set
    C_in = tuple(C.tolist()) in rows_M_set
    print(f"  A ∈ orb(M)?  {A_in}", flush=True)
    print(f"  B ∈ orb(M)?  {B_in}", flush=True)
    print(f"  C ∈ orb(M)?  {C_in}", flush=True)
    sum_ABC = A + B + C
    print(f"  A + B + C = {list(sum_ABC)}", flush=True)
    print(f"  -U_8       = {list(-U8)}", flush=True)
    matches = bool(np.all(sum_ABC == -U8))
    print(f"  matches -U_8 ?  {matches}", flush=True)

    # ---- Final summary.
    print()
    print("=" * 78)
    print("  Summary")
    print("=" * 78)
    print(f"  rank(Λ_M)               = {inv_M['rank']}")
    print(f"  elem. div.(Λ_M)         = {inv_M['elementary_divisors']}")
    print(f"  rank(Λ_{{O_6}})           = {inv_O6['rank']}")
    print(f"  elem. div.(Λ_{{O_6}})     = {inv_O6['elementary_divisors']}")
    print(f"  Λ_M = V_std ∩ Z^9 ?     = {saturated_M}")
    print(f"  Λ_{{O_6}} ⊆ Λ_M ?         = {res['in_lattice']}")
    print(f"  [Λ_M : Λ_{{O_6}}]         = {idx}")
    print(f"  3-term witness valid ?  = {matches}")

    out = {
        "phase": "9.18.S9q-β-lattice (lattice characterization)",
        "M_rep": list(M_rep),
        "O6_rep": list(O6_rep),
        "orb_sizes": {"M": int(orb_M.shape[0]),
                      "O_6": int(orb_O6.shape[0])},
        "Lambda_M": {
            "rank": inv_M["rank"],
            "elementary_divisors": inv_M["elementary_divisors"],
            "saturates_V_std": saturated_M,
        },
        "Lambda_O6": {
            "rank": inv_O6["rank"],
            "elementary_divisors": inv_O6["elementary_divisors"],
            "saturates_V_std": saturated_O6,
        },
        "A8_reference": {
            "rank": inv_A8["rank"],
            "elementary_divisors": inv_A8["elementary_divisors"],
        },
        "inclusion_O6_in_LambdaM": bool(res["in_lattice"]),
        "index_LambdaM_over_LambdaO6": idx,
        "three_term_witness": {
            "A": list(A.tolist()), "B": list(B.tolist()),
            "C": list(C.tolist()),
            "U8": list(U8.tolist()),
            "A_in_orbM": A_in, "B_in_orbM": B_in, "C_in_orbM": C_in,
            "sum_equals_minus_U8": matches,
        },
    }

    out_path = DATA / "phase_9_18_S9q_beta_lattice.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)
    print(f"\n  saved → {out_path}", flush=True)


if __name__ == "__main__":
    main()
