"""Phase 9.18.S9x-bis — Structural identification of K_L, K_R for M19.

Context (S9x results, audit-corrected 2026-04-26):
  Γ*_M19 = π_0 K_R = K_L π_0   with |K_L| = |K_R| = 72.
  K_L ≠ K_R as sets, but K_L = π_0 K_R π_0^{-1} (conjugate via π_0).
  Both have identical cycle-type spectrum.

GOAL: promote the coset structure from "verified computationally" to
"identified analytically".

Tasks:
  (Y1) Reload K_L, K_R, π_0 from S9x JSON.
  (Y2) Verify K_L = π_0 K_R π_0^{-1} explicitly.
  (Y3) Identify abstract group type by:
       - center order, derived series, abelianization
       - composition factors (subnormal series via Sylow-type analysis)
       - recognise via fingerprint among groups of order 72
  (Y4) Action of K_L on {1,..,9}:
       - orbit decomposition
       - block systems (imprimitivity)
       - test partition 3+3+3, 3+6, 6+3, transitive vs not
  (Y5) Verify u*^T S_M19(γ) = 0 for ALL 72 γ ∈ π_0 K_R (right-side).
       Re-derive the kernel via row-reduce; this is the "analytic"
       annihilation lemma.
  (Y6) Save full structural fingerprint to JSON.

Output:
  - data/phase_9_18_S9x_bis_results.json
  - data/phase_9_18_S9x_bis_output.txt
"""
from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np
from sympy import Matrix, Rational

HERE = Path(__file__).resolve().parents[2]  # <repo>/scripts/legacy/ -> <repo>/
sys.path.insert(0, str(HERE / "scripts" / "legacy"))

from phase_9_18_S9b import build_S  # noqa: E402
from phase_9_18_S9t_ter import load_bases  # noqa: E402


# ------------------------------------------------------------
# Permutation arithmetic (1-based 9-tuples)
# ------------------------------------------------------------
def perm_inv(p):
    n = len(p)
    inv = [0] * n
    for i, v in enumerate(p):
        inv[v - 1] = i + 1
    return tuple(inv)


def perm_compose(p, q):
    """p ∘ q: i ↦ p(q(i))."""
    return tuple(p[q[i] - 1] for i in range(len(p)))


def perm_id(n=9):
    return tuple(range(1, n + 1))


def perm_order(p):
    n = len(p)
    e = perm_id(n)
    cur = p
    k = 1
    while cur != e:
        cur = perm_compose(p, cur)
        k += 1
    return k


def cycle_type(p):
    n = len(p)
    seen = [False] * n
    cycles = []
    for i in range(n):
        if seen[i]:
            continue
        c = 0
        j = i
        while not seen[j]:
            seen[j] = True
            j = p[j] - 1
            c += 1
        cycles.append(c)
    return tuple(sorted(cycles, reverse=True))


def conjugate(g, h):
    """Return h g h^{-1}."""
    return perm_compose(h, perm_compose(g, perm_inv(h)))


def commutator(a, b):
    """[a,b] = a b a^{-1} b^{-1}."""
    return perm_compose(perm_compose(a, b), perm_compose(perm_inv(a), perm_inv(b)))


def subgroup_close(gens):
    """Return the subgroup generated by gens as a frozenset of tuples."""
    elems = set([perm_id(9)])
    frontier = list(elems)
    gens = list(gens)
    while frontier:
        new_frontier = []
        for x in frontier:
            for g in gens:
                xg = perm_compose(x, g)
                if xg not in elems:
                    elems.add(xg)
                    new_frontier.append(xg)
                gx = perm_compose(g, x)
                if gx not in elems:
                    elems.add(gx)
                    new_frontier.append(gx)
        frontier = new_frontier
    return elems


# ------------------------------------------------------------
# (Y3) Group-theoretic invariants
# ------------------------------------------------------------
def center(K_set):
    """Z(K) = {z ∈ K : zg = gz ∀ g ∈ K}."""
    Z = []
    for z in K_set:
        if all(perm_compose(z, g) == perm_compose(g, z) for g in K_set):
            Z.append(z)
    return Z


def derived_subgroup(K_set):
    """K' = ⟨[a,b] : a,b ∈ K⟩, intersected with K (always ⊆ K since K is subgroup)."""
    K_list = list(K_set)
    comms = set()
    for a in K_list:
        for b in K_list:
            comms.add(commutator(a, b))
    # Generate subgroup from commutators (closed under composition)
    if not comms:
        return set([perm_id(9)])
    return subgroup_close(list(comms)) & K_set


def derived_series(K_set):
    series = [K_set]
    cur = K_set
    while True:
        nxt = derived_subgroup(cur)
        if len(nxt) == len(cur):
            break
        series.append(nxt)
        cur = nxt
    return series


def abelianization_order(K_set):
    """|K / K'| = |K| / |K'|."""
    Kp = derived_subgroup(K_set)
    return len(K_set) // len(Kp)


def conjugacy_classes(K_set):
    K_list = list(K_set)
    seen = set()
    classes = []
    for g in K_list:
        if g in seen:
            continue
        cls = set()
        for h in K_list:
            cls.add(conjugate(g, h))
        seen |= cls
        classes.append(cls)
    return classes


# ------------------------------------------------------------
# (Y4) Block systems / orbits
# ------------------------------------------------------------
def orbits_of_subgroup(K_set, n=9):
    pts = set(range(1, n + 1))
    orbs = []
    while pts:
        x = min(pts)
        orb = set([x])
        frontier = [x]
        while frontier:
            new_f = []
            for y in frontier:
                for g in K_set:
                    z = g[y - 1]
                    if z not in orb:
                        orb.add(z)
                        new_f.append(z)
            frontier = new_f
        pts -= orb
        orbs.append(sorted(orb))
    return orbs


def is_transitive(K_set, n=9):
    return len(orbits_of_subgroup(K_set, n)) == 1


def find_block_systems(K_set, n=9):
    """All non-trivial block systems (partitions of {1..n} preserved by K).

    Returns list of partitions; orbit-equivalent blocks merged.
    """
    if not is_transitive(K_set, n):
        return []  # restrict to transitive case for cleanliness
    systems = []
    seen_systems = set()
    # For each pair (1, j), j != 1, compute the smallest block containing {1, j}
    for j in range(2, n + 1):
        block = {1, j}
        changed = True
        while changed:
            changed = False
            new_block = set(block)
            for g in K_set:
                for x in block:
                    new_block.add(g[x - 1])
            # The image g·block must be either equal to block or disjoint;
            # if not equal, take union (forces enlargement until block stable)
            for g in K_set:
                img = frozenset(g[x - 1] for x in block)
                if img != frozenset(block) and img & frozenset(block):
                    new_block |= img
                    changed = True
            if new_block != block:
                block = new_block
                changed = True
        # Now build the full system as the orbit of block under K
        full_partition = []
        used = set()
        for x in range(1, n + 1):
            if x in used:
                continue
            # Find the K-translate of block containing x
            # If x ∈ block, take block; else find g with g(b)=x for some b∈block
            for g in K_set:
                img = frozenset(g[b - 1] for b in block)
                if x in img:
                    full_partition.append(sorted(img))
                    used |= img
                    break
        full_partition_tuple = tuple(tuple(p) for p in sorted(full_partition))
        if full_partition_tuple not in seen_systems and len(block) < n:
            seen_systems.add(full_partition_tuple)
            systems.append([list(p) for p in full_partition_tuple])
    return systems


# ------------------------------------------------------------
# (Y3-id) Fingerprint vs known groups of order 72
# ------------------------------------------------------------
# There are 50 groups of order 72 (SmallGroup IDs 1..50). We use a compact
# fingerprint to narrow down: (|Z|, |G'|, |G/G'|, exponent, #conj classes,
# cycle-type spectrum on natural rep).
# Some named candidates of order 72:
#   - C_72 (cyclic) — abelian
#   - C_2 × C_36, C_3 × C_24, ...      (abelian)
#   - S_3 × A_4   (non-abelian, |Z|=1)
#   - S_3 × D_6   (non-abelian)
#   - (C_3 × C_3) ⋊ D_4
# We won't try full enumeration (50 cases); we'll output all invariants
# so that the user can match against GAP/Sage tables.

def exponent_of(K_set):
    return max(perm_order(g) for g in K_set)


def order_distribution(K_set):
    return dict(Counter(perm_order(g) for g in K_set))


# ------------------------------------------------------------
# (Y5) Annihilation lemma: u*^T S_M19(γ) v = 0 for γ ∈ Γ*
# ------------------------------------------------------------
def kernel_annihilation_test(L_M19, Gamma_star, u_star_8):
    """For each γ ∈ Γ*, build S_8(γ) (left version), check u*^T S_8 = 0.

    We use the LEFT side here (since side-mix in S9x was 72/72 left).
    Returns: (n_certified, n_total, max_residual_norm_inf).
    """
    n = 9
    n_total = len(Gamma_star)
    n_cert = 0
    max_res = 0
    u_arr = np.array(u_star_8, dtype=np.int64)
    for gamma in Gamma_star:
        S_full = build_S(L_M19, gamma)
        # build_S returns the 9x9 (or 8x8) sumcheck matrix. Determine
        # convention: S9x uses S_8 (8x8) after projecting by Σ=0.
        S = np.array(S_full, dtype=np.int64)
        if S.shape == (9, 9):
            # Project by removing last row+col is incorrect; use 8x8 from
            # build_S directly if available. For now, test on full 9-vec:
            u9 = np.array(u_star_8 + [-(sum(u_star_8))]
                          if len(u_star_8) == 8
                          else u_star_8, dtype=np.int64)
            res = u9 @ S
        else:
            res = u_arr @ S
        rn = int(np.max(np.abs(res)))
        if rn == 0:
            n_cert += 1
        if rn > max_res:
            max_res = rn
    return n_cert, n_total, max_res


# ------------------------------------------------------------
# Main driver
# ------------------------------------------------------------
def main():
    data_dir = HERE / "data"
    in_json = data_dir / "phase_9_18_S9x_results.json"
    if not in_json.exists():
        print(f"ERROR: {in_json} not found. Run phase_9_18_S9x.py first.")
        return
    with open(in_json) as f:
        S9x = json.load(f)

    K_L = [tuple(p) for p in S9x["K_L_elements"]]
    K_R = [tuple(p) for p in S9x["K_R_elements"]]
    K_L_set = set(K_L)
    K_R_set = set(K_R)
    u_star = list(S9x["u9_star"])
    L_M19 = S9x["M19_grid"]
    Gamma_star = [tuple(p) for p in S9x.get("Gamma_star_perms", [])]
    # π_0: any element of Γ*. Choice: lex-min (canonical anchor).
    if Gamma_star:
        pi_0 = min(Gamma_star)
    else:
        pi_0 = None

    print("=" * 78)
    print("Phase 9.18.S9x-bis — Structural identification of K_L, K_R")
    print("=" * 78)
    print(f"|K_L| = {len(K_L_set)}, |K_R| = {len(K_R_set)}")
    print(f"K_L == K_R as sets? {K_L_set == K_R_set}")
    print(f"K_L ∩ K_R: |.| = {len(K_L_set & K_R_set)}")
    print(f"u9* = {u_star}")
    if pi_0:
        print(f"π_0 = {list(pi_0)}")

    # ---- (Y2) K_L = π_0 K_R π_0^{-1}? ----
    print()
    print("=" * 78)
    print("(Y2) Conjugacy K_L = π_0 K_R π_0^{-1} ?")
    print("=" * 78)
    if pi_0 is not None:
        conj_KR = set(conjugate(g, pi_0) for g in K_R_set)
        equal = (conj_KR == K_L_set)
        print(f"   π_0 K_R π_0^{{-1}} == K_L ? {equal}")
        if not equal:
            # Try other direction
            conj_KL = set(conjugate(g, perm_inv(pi_0)) for g in K_L_set)
            equal2 = (conj_KL == K_R_set)
            print(f"   π_0^{{-1}} K_L π_0 == K_R ? {equal2}")
            equal = equal or equal2
        Y2_conjugate = bool(equal)
    else:
        Y2_conjugate = None
        print("   π_0 unavailable in JSON; skipping conjugacy check")

    # ---- (Y3) Group-theoretic invariants on K_L (mirror on K_R) ----
    print()
    print("=" * 78)
    print("(Y3) Group invariants of K_L")
    print("=" * 78)
    invariants = {}
    for label, K in [("K_L", K_L_set), ("K_R", K_R_set)]:
        Z = center(K)
        Kp = derived_subgroup(K)
        ds = derived_series(K)
        ab_order = abelianization_order(K)
        cc = conjugacy_classes(K)
        exp = exponent_of(K)
        ord_dist = order_distribution(K)
        info = {
            "order": len(K),
            "center_order": len(Z),
            "derived_subgroup_order": len(Kp),
            "abelianization_order": ab_order,
            "derived_series_orders": [len(s) for s in ds],
            "is_solvable": (len(ds[-1]) == 1),
            "n_conjugacy_classes": len(cc),
            "exponent": exp,
            "order_distribution": ord_dist,
        }
        print(f"\n  {label}:")
        for k, v in info.items():
            print(f"    {k}: {v}")
        invariants[label] = info

    # Quick sanity: 72 = 2^3 · 3^2. The certified paper package now
    # identifies the group through a normal regular C_3^2 subgroup and
    # D_4 point stabilizer, not through a SmallGroup ID.

    # ---- (Y4) Action on 9 points ----
    print()
    print("=" * 78)
    print("(Y4) Action of K_L on {1,..,9}")
    print("=" * 78)
    orbs_L = orbits_of_subgroup(K_L_set)
    orbs_R = orbits_of_subgroup(K_R_set)
    print(f"  K_L orbits: {orbs_L}  (transitive? {len(orbs_L)==1})")
    print(f"  K_R orbits: {orbs_R}  (transitive? {len(orbs_R)==1})")

    block_sys_L = []
    block_sys_R = []
    if len(orbs_L) == 1:
        block_sys_L = find_block_systems(K_L_set)
        print(f"  K_L non-trivial block systems: {len(block_sys_L)}")
        for bs in block_sys_L:
            sizes = sorted([len(b) for b in bs])
            print(f"    sizes={sizes}: {bs}")
    if len(orbs_R) == 1:
        block_sys_R = find_block_systems(K_R_set)
        print(f"  K_R non-trivial block systems: {len(block_sys_R)}")
        for bs in block_sys_R:
            sizes = sorted([len(b) for b in bs])
            print(f"    sizes={sizes}: {bs}")

    # ---- (Y6) Save ----
    out = {
        "phase": "9.18.S9x-bis",
        "K_L_eq_K_R": K_L_set == K_R_set,
        "K_L_inter_K_R_size": len(K_L_set & K_R_set),
        "Y2_conjugate_via_pi0": Y2_conjugate,
        "invariants": invariants,
        "orbits_K_L": orbs_L,
        "orbits_K_R": orbs_R,
        "K_L_block_systems": block_sys_L,
        "K_R_block_systems": block_sys_R,
    }
    out_json = data_dir / "phase_9_18_S9x_bis_results.json"
    with open(out_json, "w") as f:
        json.dump(out, f, indent=2, default=str)
    print(f"\nSaved: {out_json}")


if __name__ == "__main__":
    main()
