"""phase_9_18_extra_canonical_ranks.py
========================================
P1.1 — Canonical-rank scan on 400 sampled 9x9 Sudoku grids.

For each grid L, compute the **canonical** rank of E := L - 5 J on
V_{std,9} (i.e. the un-relabeled rank, gamma = identity). The grids are
generated by ``sample_sudoku`` (used by phase 9.13 / 9.18 throughout the
project) with frozen seed range 20260440 .. 20260440 + N - 1, matching
the M-corpus convention.

Output JSON (committed under ``data/``) contains:
  - the histogram of canonical ranks observed,
  - the smallest seed achieving each rank,
  - the SHA-256 of the (sorted) full rank list,
  - the produced_utc.

Frozen seed: ``BASE_SEED = 20260440``, ``N_GRIDS = 400``.
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import random
import sys
from collections import Counter
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
# HERE = <repo>/scripts/legacy/
# PROJECT = <repo>/
PROJECT = HERE.parent.parent
sys.path.insert(0, str(PROJECT / "scripts" / "legacy"))
from phase_9_13 import is_sudoku, sample_sudoku  # noqa: E402

BASE_SEED = 20260440
N_GRIDS = 400
DATA_OUT = PROJECT / "data" / "phase_9_18_extra_canonical_ranks.json"


def _projector_basis(n: int) -> np.ndarray:
    """Return the n x (n-1) matrix P_n with columns e_i - e_n, 1 <= i <= n-1."""
    P = np.zeros((n, n - 1), dtype=np.int64)
    for i in range(n - 1):
        P[i, i] = 1
        P[n - 1, i] = -1
    return P


def canonical_rank(L: np.ndarray) -> int:
    """rank(L - 5 J_9) restricted to V_{std,9} = ker(1^T)."""
    n = L.shape[0]
    assert n == 9
    E = L.astype(np.int64) - 5 * np.ones((n, n), dtype=np.int64)
    P = _projector_basis(n)
    Ehat = P.T @ E @ P  # 8 x 8 over Z
    return int(np.linalg.matrix_rank(Ehat))


def main() -> Path:
    print(f"[P1.1] Canonical-rank scan, N={N_GRIDS}, BASE_SEED={BASE_SEED}")
    seeds_used: list[int] = []
    ranks: list[int] = []
    seen: set[tuple] = set()
    seed = BASE_SEED
    first_seed_per_rank: dict[int, int] = {}
    while len(ranks) < N_GRIDS:
        rng = random.Random(seed)
        L = sample_sudoku(rng)
        seed += 1
        key = tuple(L.flatten().tolist())
        if key in seen:
            continue
        if not is_sudoku(L):
            continue
        seen.add(key)
        r = canonical_rank(L)
        ranks.append(r)
        seeds_used.append(seed - 1)
        if r not in first_seed_per_rank:
            first_seed_per_rank[r] = seed - 1
            print(f"  first seed with canonical rank {r}: {seed - 1}")
        if len(ranks) % 100 == 0:
            print(f"  scanned {len(ranks)}/{N_GRIDS}")

    histogram = dict(Counter(ranks))
    sorted_ranks = sorted(histogram.items())
    print(f"[P1.1] rank histogram (canonical, gamma=id): {sorted_ranks}")

    payload_for_hash = {
        "n": 9,
        "n_grids": N_GRIDS,
        "base_seed": BASE_SEED,
        "rank_list_sorted": sorted(ranks),
    }
    canonical_blob = json.dumps(
        payload_for_hash, sort_keys=True, ensure_ascii=False
    ).encode("utf-8")
    sha = hashlib.sha256(canonical_blob).hexdigest()

    out = {
        "result_id": "phase_9_18_extra_canonical_ranks",
        "n": 9,
        "n_grids": N_GRIDS,
        "base_seed": BASE_SEED,
        "histogram": {str(k): int(v) for k, v in sorted_ranks},
        "first_seed_per_rank": {
            str(k): int(v) for k, v in sorted(first_seed_per_rank.items())
        },
        "rank_list_sha256": sha,
        "produced_utc": _dt.datetime.now(_dt.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z"),
        "schema_version": 1,
    }

    DATA_OUT.parent.mkdir(parents=True, exist_ok=True)
    with DATA_OUT.open("w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"[P1.1] wrote {DATA_OUT.relative_to(PROJECT)}")
    return DATA_OUT


if __name__ == "__main__":
    main()
