r"""fig4_A8_saturation.py
=========================
This paper ?7 --
this paper: the row-band image lattice $\Lambda_M$ generated by base$_1$
under the M-orbit equals the column-stack image lattice
$\Lambda_{O_6}$, and both saturate the root lattice $A_8$ (the
intersection of $V_{\mathrm{std},9}$ with $\mathbb{Z}^9$).

This is a Hasse-style schematic; no numerical computation is involved
beyond locating the boxes.
"""
from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

HERE = Path(__file__).resolve().parent


def _box(ax, xy, w, h, text, fc="white", ec="black", fs=10):
    x, y = xy
    ax.add_patch(FancyBboxPatch(
        (x - w / 2, y - h / 2), w, h,
        boxstyle="round,pad=0.05,rounding_size=0.08",
        facecolor=fc, edgecolor=ec, linewidth=1.0,
    ))
    ax.text(x, y, text, ha="center", va="center", fontsize=fs)


def _arrow(ax, p, q, label=None, double=False):
    style = "<|-|>" if double else "-|>"
    ax.add_patch(FancyArrowPatch(
        p, q, arrowstyle=style, mutation_scale=12,
        color="black", lw=1.0, shrinkA=18, shrinkB=18,
    ))
    if label:
        mx = (p[0] + q[0]) / 2
        my = (p[1] + q[1]) / 2
        ax.text(mx + 0.1, my, label, fontsize=9, ha="left", va="center")


def main() -> Path:
    fig, ax = plt.subplots(figsize=(6.4, 4.0))

    # Top: full ambient.
    _box(ax, (3, 3.6), 3.6, 0.8,
         r"$V_{\mathrm{std},9} \cap \mathbb{Z}^9 \;=\; A_8$",
         fc="#eef3ff")

    # Middle row: Lambda_M and Lambda_{O_6}.
    _box(ax, (1.4, 2.1), 2.2, 0.8,
         r"$\Lambda_M$  (row-band image)", fc="#fff3cd")
    _box(ax, (4.6, 2.1), 2.2, 0.8,
         r"$\Lambda_{O_6}$  (col-stack image)", fc="#fff3cd")

    # Bottom: equality.
    _box(ax, (3, 0.6), 3.4, 0.8,
         r"$\Lambda_M = \Lambda_{O_6} = A_8$"
         r"  (Certified Proposition D)",
         fc="#d4edda")

    # Inclusions (top->middle).
    _arrow(ax, (1.4, 3.2), (1.4, 2.5), label=r"$\subseteq$")
    _arrow(ax, (4.6, 3.2), (4.6, 2.5), label=r"$\subseteq$")

    # Equalities (middle->bottom).
    _arrow(ax, (1.4, 1.7), (3.0, 1.0), label=r"$=$")
    _arrow(ax, (4.6, 1.7), (3.0, 1.0), label=r"$=$")

    # Cross equality (saturation = full).
    _arrow(ax, (1.4, 2.5), (4.6, 2.5), label=r"$=$ (saturation)",
           double=True)

    ax.set_xlim(-0.2, 6.2)
    ax.set_ylim(0, 4.2)
    ax.set_aspect("auto")
    ax.set_xticks([])
    ax.set_yticks([])
    for s in ("top", "right", "left", "bottom"):
        ax.spines[s].set_visible(False)

    fig.suptitle(
        r"$A_8$-saturation:  $\Lambda_M = \Lambda_{O_6} = A_8$",
        fontsize=11, y=0.99,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.96))

    out_pdf = HERE / "fig4_A8_saturation.pdf"
    out_png = HERE / "fig4_A8_saturation.png"
    fig.savefig(out_pdf, metadata={"CreationDate": None, "ModDate": None})
    fig.savefig(out_png, dpi=200)
    plt.close(fig)
    print(f"[OK] {out_pdf.name}, {out_png.name}")
    return out_pdf


if __name__ == "__main__":
    main()
